appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: YpMjpjbPQbX6Ofxhb3zhDT1Xf4GEasVoCxdHa3vaFemAHcV0aLNqB7PtPYycgg0H3czmsRFYJcgQeVSCwF8qrQXAcWF4xt7kcix8jzX7HFsaqSOcLuFYIiGXITY6ZfTiJg8wnqbwhBFgDd7KTbkjOYi/vn2HAADxgKUNbl+8iCiPg6h57bI6jYVlksu3hoMA/MSbm+adrgCSM+SroHMvIWzCauDqzAjOdXe0S6DN+B42p3iKTb41AJCjJqiCikl2b0DiyBXJGokT1qquO+fW71QAe4WUBCn6mokGpsiljYd62BCNJI61Z57smOQg5jDaU0UvD2kk2wtT0gRbFDTfgU7GZlXdQgvZrvEqf57uqjnTPxBl3MK84/qex43Ptnyvmp6PMVHrHae4hJitEG3BWuvZi1PO3BZngPS0tUpMICmsTpSmLq/jUZrS00R4GfFdyuPwnSSvW+AB4yVh4G8tBHoWwCLOUwpREiZzcyeOM2J0PUK9d+XwmNaNDldgYgV757tCd5Pm1+TJr7m/EgBr7FxxxdaqpOq3qkXXJNxr025rTGwhNeoem56/YUDEqHgDQpqKLG8mO4ODlpVZoxSwbSPR9K/Wu3F+LvV2OJhFI4t9+Zg/SV0PtJuBWSOt2e7CvPx78OyqqFW+8Vg7jJK8yroqysjPEkoVIGhXKxFDT88=}
bot:
  automerge: true
