travis:
  secure:
    BINSTAR_TOKEN: cjqXOaVD3hZUj2DvxZdvI5BZvJQLbiE+euuASvpeDgPJmD87FZqnZLocB64Khw7X50vbzzUxXJtnjXA/kc/28bG/emF9zx1adZ/C1+aQT0BWYg35sGzj1hj/NiSPsHC0i22A5HACWrsEr6ivoHdMcoCkPtdxjzgFh2ukDvOpgvqzYgOTqwACnh7QKrSXEDtiKO3uV8vmh5iQRq5vHbZgZezSkbqzkEbjm9BZL9tMIIUMh6aPmUfj8oetBoeWDRIv1u0YlSEHN5EcLUpsCibe3ah+RcBAdu+VGjINMCKBNl59FYT7HdAtBeOu167qKZb3P+jbq3h9sVTBNkoCyQrvbzbAVRuWNlmySspE5BADQwFs5nHWUzB8TKwIQyqSwA1PVnHyy9TLW7GwcriDZPJpIhMSAB57ewuaH/BMTujLfu9ovjgqrkQ/EMfwQthJ/XCmZWgfA+InQz1dUp+QWnyCJLqWYKg1BBFCvc+TwBYW0lISTXvZPMy5vuLkarvJHSGE4SIHod8yoQxak5dl7l1M/KPB8yVhScgWq+8nK2eKsiqtrJ2CIcm9/tsXCNk1B5ArbygxQg8dimvhBJNNABaxcm+yTz8ZRDbaHUGFDLiuM1+7uywvvAZsTBq+xl5tZEV4HjPW630KF1S4Dek7qz3L487Zce0MxH8AmkfRLTRJ6I0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
